# Site Settings
title: Laptop Chemistry
author:
  name: Brad Dallin
  email: bradley.dallin.phd@gmail.com
description: >
  "My digital workspace for computational chemistry research,
  cheminformatics tools, and scientific computing projects.
  Sharing thoughts on methods, discoveries, and open source
  contributions that catch my attention in the world of scientific
  computing."


# Build settings
remote_theme: jekyll/minima@593a05a
# TO-DO: Clone Minima and/or build locally
# theme: minima


# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag


# Web Verification
webmaster_verifications:
  google: c60f72eec49f666f
  # bing: 
  # alexa: 
  # yandex: 
  # baidu: 
  # facebook: 


# Include
include:
  - /assets/favicon/favicon.ico


# Site Collections
collections:
  methods:
    output: true


# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: auto

  # Site Navigation
  nav_pages:
    - methods.md
    - about.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false


  # Social Media Links
  # Entry keys:
  # * title    Tooltip rendered on hovering over icon.
  # * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  # * url      Full URL of social profile.
  social_links:
   - title: GitHub
     icon: github
     url: "https://github.com/brad-dallin"
   - title: LinkedIn
     icon: linkedin
     url: "https://www.linkedin.com/in/bradley-dallin/"
